version: 0.2
env:
  variables:
    IMAGE_REPO_NAME: phoenix-build
    IMAGE_TAG: Latest
  parameter-store:
    DOCKERHUB_TOKEN: /CodeBuild/DOCKERHUB_TOKEN
    DOCKERHUB_USER: /CodeBuild/DOCKERHUB_USER
    AWS_ACCOUNT_ID: /CodeBuild/AWS_ACCOUNT_ID
phases:
  pre_build:
    commands:
      - echo Started on `date`
      - echo docker info
      - aws --version
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin
  build:
    commands:
      - docker build -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} .
      - docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}

  post_build:
    commands:
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}
      - echo Build completed on `date`
