AWSTemplateFormatVersion: 2010-09-09
Description: 'Stack for CodePipeline'

Resources:
  CodeBuildPhoenix:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: phoenix-build-project
      Artifacts:
        Type: "no_artifacts"
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: us-east-1
            Type: PLAINTEXT
          - Name: DOCKERHUB_USER
            Value: /CodeBuild/DOCKERHUB_USER
            Type: PARAMETER_STORE
          - Name: DOCKERHUB_TOKEN
            Value: /CodeBuild/DOCKERHUB_TOKEN
            Type: PARAMETER_STORE
          - Name: AWS_ACCOUNT_ID
            Value: /CodeBuild/AWS_ACCOUNT_ID
            Type: PARAMETER_STORE
        PrivilegedMode: false
      ServiceRole: arn:aws:iam::075897120159:role/CodeBuildRole
      Source:
        Type: GITHUB
        Location: https://github.com/Raptorex65/phoenix-project.git

