AWSTemplateFormatVersion: 2010-09-09
Description: Load balancing nested stack template

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id

  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The subnets that the load balancer will span

  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id 
    Description: The security group that will be attached to the instance

Resources:
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Subnets: !Ref Subnets
      IpAddressType: ipv4

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: 3000
      Protocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: '/'
      HealthCheckPort: '3000'
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: '200'
      TargetGroupAttributes:
        - 
          Key: 'deregistration_delay.timeout_seconds'
          Value: 10
      Tags:
        - Key: Name
          Value: 'target-group'

  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - 
          TargetGroupArn: !Ref TargetGroup
          Type: forward

Outputs:
  LoadBalancerDNSName:
    Description: DNS name of the application load balancer
    Value: !GetAtt ApplicationLoadBalancer.DNSName

  LoadBalancerFullName:
    Description: LoadBalancerFullName for ALBRequestCountScalingPolicy
    Value: !GetAtt ApplicationLoadBalancer.LoadBalancerFullName

  TargetGroupARN:
    Description: ARN of the load balancer target group
    Value: !Ref TargetGroup
  
  TargetGroupFullName:
    Description: ARN of the load balancer target group
    Value: !GetAtt TargetGroup.TargetGroupFullName

